export default {
	"Afghanistan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1eb.png",
	"Albania": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1f1.png",
	"Angola": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1f4.png",
	"Argentina": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1f7.png",
	"Armenia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1f2.png",
	"Azerbaijan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e6_1f1ff.png",
	"Bahamas": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1f8.png",
	"Bangladesh": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1e9.png",
	"Belarus": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1fe.png",
	"Belgium": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1ea.png",
	"Bolivia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1f4.png",
	"Bosnia and Herzegovina": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1e6.png",
	"Brazil": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1f7.png",
	"Bulgaria": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e7_1f1ec.png",
	"Cambodia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1ed.png",
	"Cameroon": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1f2.png",
	"Canada": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1e6.png",
	"Cape Verde": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1fb.png",
	"Chad": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1e9.png",
	"China": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1f3.png",
	"Colombia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1f4.png",
	"Comoros": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1f2.png",
	"Costa Rica": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1f7.png",
	"Croatia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ed_1f1f7.png",
	"Cuba": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1fa.png",
	"Cyprus": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1fe.png",
	"Czech Republic": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1ff.png",
	"Democratic Republic of the Congo": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e8_1f1ec.png",
	"Denmark": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e9_1f1f0.png",
	"Dominican Republic": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e9_1f1f4.png",
	"East Timor": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1f1.png",
	"Ecuador": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ea_1f1e8.png",
	"Egypt": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ea_1f1ec.png",
	"Ethiopia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ea_1f1f9.png",
	"Finland": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1eb_1f1ee.png",
	"France": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1eb_1f1f7.png",
	"Germany": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e9_1f1ea.png",
	"Ghana": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1ed.png",
	"Greece": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1f7.png",
	"Greenland": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1f1.png",
	"Guam": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1fa.png",
	"Guatemala": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1f9.png",
	"Guinea": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1f3.png",
	"Haiti": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ed_1f1f9.png",
	"Honduras": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ed_1f1f3.png",
	"Hungary": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ed_1f1fa.png",
	"Indonesia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1e9.png",
	"Iran": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1f7.png",
	"Iraq": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1f6.png",
	"Ireland": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1ea.png",
	"Israel": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1f1.png",
	"Italy": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ee_1f1f9.png",
	"Japan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ef_1f1f5.png",
	"Jordan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ef_1f1f4.png",
	"Kazakhstan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1ff.png",
	"Kenya": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1ea.png",
	"Kiribati": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1ee.png",
	"Kosovo": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ea_1f1f7.png",
	"Kyrgyzstan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1ec.png",
	"Laos": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1e6.png",
	"Latvia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1fb.png",
	"Lebanon": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1e7.png",
	"Lithuania": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1f9.png",
	"Luxembourg": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1fa.png",
	"Macedonia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1f0.png",
	"Madagascar": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1ec.png",
	"Malaysia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1fe.png",
	"Maldives": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1fb.png",
	"Mali": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1f1.png",
	"Malta": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1f9.png",
	"Mexico": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1fd.png",
	"Micronesia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1eb_1f1f2.png",
	"Mongolia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1f3.png",
	"Morocco": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1e6.png",
	"Mozambique": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1ff.png",
	"Myanmar": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f2_1f1f2.png",
	"Namibia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1e6.png",
	"Netherlands": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1f1.png",
	"New Zealand": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1ff.png",
	"Nicaragua": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1ee.png",
	"Niger": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1ea.png",
	"Nigeria": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1ec.png",
	"North Korea": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1f5.png",
	"Norway": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f3_1f1f4.png",
	"Pakistan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1f0.png",
	"Palestinian Territory": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1f8.png",
	"Panama": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1e6.png",
	"Papua New Guinea": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1ec.png",
	"Peru": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1ea.png",
	"Philippines": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1ed.png",
	"Pitcairn": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1f3.png",
	"Poland": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1f1.png",
	"Portugal": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f5_1f1f9.png",
	"Reunion": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1e9_1f1ef.png",
	"Russia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f7_1f1fa.png",
	"Saint Kitts and Nevis": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1f3.png",
	"Serbia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f7_1f1f8.png",
	"Sierra Leone": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f8_1f1f1.png",
	"Slovenia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f8_1f1ee.png",
	"South Africa": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ff_1f1e6.png",
	"South Korea": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f0_1f1f7.png",
	"Spain": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ea_1f1f8.png",
	"Sri Lanka": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f1_1f1f0.png",
	"Sweden": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f8_1f1ea.png",
	"Syria": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f8_1f1fe.png",
	"Taiwan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1fc.png",
	"Tanzania": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1ff.png",
	"Thailand": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1ed.png",
	"Trinidad and Tobago": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1f9.png",
	"Tunisia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1f3.png",
	"Turkmenistan": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1f9_1f1f2.png",
	"Uganda": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fa_1f1ec.png",
	"Ukraine": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fa_1f1e6.png",
	"United Kingdom": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ec_1f1e7.png",
	"United States": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fa_1f1f8.png",
	"Uruguay": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fa_1f1fe.png",
	"Venezuela": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fb_1f1ea.png",
	"Vietnam": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fb_1f1f3.png",
	"Yemen": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1fe_1f1ea.png",
	"Zambia": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ff_1f1f2.png",
	"Zimbabwe": "https://noto-website-2.storage.googleapis.com/emoji/emoji_u1f1ff_1f1fc.png"
}